/*
 * Simple ToDo API
 *
 * This is a simple API for managing a TODO List
 *
 * API version: 1.0.0
 * Contact: recruiting@dfsco.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/aweiker/ToDo/1.0.0/",
		Index,
	},

	Route{
		"AddList",
		strings.ToUpper("Post"),
		"/aweiker/ToDo/1.0.0/lists",
		AddList,
	},

	Route{
		"AddTask",
		strings.ToUpper("Post"),
		"/aweiker/ToDo/1.0.0/list/{id}/tasks",
		AddTask,
	},

	Route{
		"GetList",
		strings.ToUpper("Get"),
		"/aweiker/ToDo/1.0.0/list/{id}",
		GetList,
	},

	Route{
		"PutTask",
		strings.ToUpper("Post"),
		"/aweiker/ToDo/1.0.0/list/{id}/task/{taskId}/complete",
		PutTask,
	},

	Route{
		"SearchLists",
		strings.ToUpper("Get"),
		"/aweiker/ToDo/1.0.0/lists",
		SearchLists,
	},
}
